# render.yaml
services:
  - name: sci-fi-app-backend
    type: web
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://jefftkddan:AocetUls99bS7EKl@cluster0.vva0aat.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

  - name: sci-fi-app-frontend
    type: web
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
