# render.yaml
services:
  - name: sci-fi-app-backend
    type: web
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGODB_URI
        value: "your_mongodb_connection_string"

  - name: sci-fi-app-frontend
    type: web
    env: static
    plan: free
    buildCommand: npm install && npm run build --prefix frontend
    staticPublishPath: frontend/dist
