services:
  - type: web
    name: sci-fi-app-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: MONGODB_URI
        value: YOUR_MONGODB_URI
    autoDeploy: true
    env: 
      PYTHON_VERSION: "3.9"

  - type: static
    name: sci-fi-app-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
    autoDeploy: true
